export const NEW_JOB_POSTING = 'NEW_JOB_POSTING';
export const STUDENT_PROFILE_DATA = 'STUDENT_PROFILE_DATA';
export const STUDENT_DEMOGRAPHICS_DATA = 'STUDENT_DEMOGRAPHICS_DATA';
export const GET_ALL_JOBS = 'GET_ALL_JOBS';

export const NEW_REVIEW_POSTING = 'NEW_REVIEW_POSTING';
export const NEW_SALARY_POSTING = 'NEW_SALARY_POSTING';
export const GET_SALARY = 'GET_SALARY';
export const GET_REVIEW = 'GET_REVIEW';
export const GET_COMPANY_OVERVIEW = 'GET_COMPANY_OVERVIEW';
export const GET_JOBS = 'GET_JOBS';
export const GET_POSITIVE_REVIEW = 'GET_POSITIVE_REVIEW';
export const GET_NEGATIVE_REVIEW = 'GET_NEGATIVE_REVIEW';
export const GET_FEATURED_REVIEW = 'GET_FEATURED_REVIEW';
<<<<<<< Updated upstream
export const GET_AVERAGE_RATING = 'GET_AVERAGE_RATING';
=======
export const GET_AVERAGE_RATING = 'GET_AVERAGE_RATING';
>>>>>>> Stashed changes
