export const NEW_JOB_POSTING = 'NEW_JOB_POSTING';
export const STUDENT_PROFILE_DATA = 'STUDENT_PROFILE_DATA';
export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_JOB_APPLICANT_DETAILS = 'GET_JOB_APPLICANT_DETAILS';
export const UPDATE_APPLICANT_STATUS = 'UPDATE_APPLICANT_STATUS';
